#!/bin/bash
find . -name '*.aux' -delete
find . -name '*.log' -delete
find . -name '*.lof' -delete
find . -name '*.bbl' -delete
find . -name '*.blg' -delete
find . -name '*.thm' -delete
find . -name '*.toc' -delete
find . -name '*.out' -delete
find . -name '*.loa' -delete
find . -name '*.synctex.gz' -delete
